# Generated by Django 5.1.3 on 2024-12-15 03:55

from django.db import migrations



def transfer_tags(apps, schema_editor):
    Article = apps.get_model('webapp.Article')
    for article in Article.objects.all():
        article.tags.set(article.tags_old.all())


def rollback_transfer(apps, schema_editor):
    Article = apps.get_model('webapp.Article')
    for article in Article.objects.all():
        article.tags_old.set(article.tags.all())


class Migration(migrations.Migration):
    dependencies = [
        # Оставьте здесь свой номер миграции
        ('webapp', '00xx_auto_20200806_2030'),
    ]


    operations = [
        migrations.RunPython(transfer_tags, rollback_transfer)
    ]

class Migration(migrations.Migration):
    dependencies = [
        ('webapp', '0003_article_tags_alter_article_tags_old'),
    ]
    operations = [
        migrations.RunPython(transfer_tags, rollback_transfer),
    ]
