# Generated by Django 5.1.3 on 2024-12-15 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20241215_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags_old',
        ),
        migrations.DeleteModel(
            name='ArticleTag',
        ),
    ]
